apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-helmrelease-fullaccess
rules:
  - apiGroups:
      - "helm.toolkit.fluxcd.io"
    resources:
      - "helmreleases"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "projectcontour.io"
    resources:
      - "httpproxies"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "update"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "configmaps"
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
    verbs:
      - "list"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name}}-helmrelease-fullaccess
subjects:
  - kind: ServiceAccount
    name: workspace-service
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name}}-helmrelease-fullaccess
  apiGroup: rbac.authorization.k8s.io
