---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-estimator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-cost-estimator
---
apiVersion: v1
kind: Secret
metadata:
  name: cost-estimator-secret
  annotations:
    kubernetes.io/service-account.name: cost-estimator
type: kubernetes.io/service-account-token
