{{- if .Values.configSecret.create -}}
{{- $issuer := .Values.config.issuer }}
{{- if not $issuer -}}
{{- $issuer = printf "http://%s-dex.%s.svc.cluster.local:5556/dex" .Release.Name .Release.Namespace }}
{{- end }}
{{- $config := .Values.config | merge (dict "issuer" $issuer) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.configSecretName" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ $config | toYaml | b64enc | quote }}
{{- end }}
