apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-runner-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: query-runner-worker
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: query-runner-worker
  template:
    metadata:
      labels:
        app: query-runner-worker
    spec:
      containers:
        - name: query-runner-worker
          image: {{ .Values.kaytu.queryRunner.worker.image.repo }}:{{- dig .Values.kaytu.envType .Values.kaytu.queryRunner.worker.image.tag.dev .Values.kaytu.queryRunner.worker.image.tag }}
          command: ["/query-runner-worker"]
          args:
            - --id=$(WORKER_ID)
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 100Mi
          env:
            #- name: STEAMPIPE_HOST
            #  value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
            #- name: STEAMPIPE_PORT
            #  value: "9193"
            #- name: STEAMPIPE_DB
            #  value: "steampipe"
            #- name: STEAMPIPE_USERNAME
            #  value: "steampipe"
            #- name: STEAMPIPE_PASSWORD
            #  value: "abcd"
            #- name: STEAMPIPE_SSLMODE
            #  value: "disable"
            - name: STEAMPIPE_LOG_LEVEL
              value: "WARN"
            - name: STEAMPIPE_MAX_PARALLEL
              value: "50"
            - name: STEAMPIPE_CACHE
              value: "false"
            - name: STEAMPIPE_UPDATE_CHECK
              value: "false"
            - name: NATS_URL
              value: "{{ .Release.Namespace }}-nats-{{ .Release.Namespace }}.{{ .Release.Namespace }}.svc.cluster.local:4222"
{{- include "elastic.envs" . | indent 12 }}
            - name: ONBOARD_BASEURL
              value: "http://onboard-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: COMPLIANCE_BASEURL
              value: "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
            - name: SCHEDULER_BASEURL
              value: "http://describe-scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
            - name: INVENTORY_BASEURL
              value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
            - name: METADATA_BASEURL
              value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: ESSINK_BASEURL
              value: "http://es-sink-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: PENNYWISE_BASE_URL
              value: "http://pennywise-server-service.kaytu-octopus.svc.cluster.local:8080"

            - name: PROMETHEUS_PUSH_ADDRESS
              value: "prom-system-prometheus-pushgateway.prom-system.svc.cluster.local:9091"

            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SERVICE_NAME
              value: "query-runner-worker"
            - name: JAEGER_SAMPLE_RATE
              value: "0.0005"