apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: namespace-issuer-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: namespace-issuer-cert
  duration: 9000h # ~1year
  renewBefore: 360h # 15d
  commonName: Test CA
  isCA: true
  privateKey:
    size: 2048
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: namespace-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: namespace-issuer-cert