{{- $describeSchedulerUserPassword := "" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
{{- if $secret }}
{{- $describeSchedulerUserPassword = index $secret.data "describeSchedulerUserPassword" | b64dec | default $describeSchedulerUserPassword }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: gf-ds-{{ .Release.Namespace }}
  namespace: prom-system
  annotations:
    "helm.sh/hook-weight": "999"
  labels:
    grafana_datasource: "1"
stringData:
  pg-db.yaml: |-
    apiVersion: 1
    datasources:
      - name: {{ .Release.Namespace }}
        type: postgres
        url: {{ .Values.postgres.name }}.{{ .Release.Namespace }}.svc.cluster.local:5432
        user: describe_scheduler
        database: describe
        secureJsonData:
          password: '{{ $describeSchedulerUserPassword }}'
          database: describe
        jsonData:
          database: describe
          sslmode: 'disable' # disable/require/verify-ca/verify-full
          maxOpenConns: 0 # Grafana v5.4+
          maxIdleConns: 2 # Grafana v5.4+
          connMaxLifetime: 14400 # Grafana v5.4+
          postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
        # <bool> allow users to edit datasources from the UI.
        editable: false
      - name: {{ .Release.Namespace }}-steampipe
        type: postgres
        url: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local:9193
        user: steampipe
        database: steampipe
        secureJsonData:
          password: 'abcd'
          database: steampipe
        jsonData:
          database: steampipe
          sslmode: 'disable' # disable/require/verify-ca/verify-full
          maxOpenConns: 0 # Grafana v5.4+
          maxIdleConns: 2 # Grafana v5.4+
          connMaxLifetime: 14400 # Grafana v5.4+
          postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
          timescaledb: false
        # <bool> allow users to edit datasources from the UI.
        editable: false