apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy-route
  namespace: {{ .Release.Namespace }}
spec:
  routes:
    - conditions:
        - prefix: /integration
      timeoutPolicy:
        response: 60s
      services:
        - name: integration-service
          port: 8000
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/integration
            replacement: /
    - conditions:
        - prefix: /assistant
      timeoutPolicy:
        response: 60s
      services:
        - name: assistant-service
          port: 8000
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/assistant
            replacement: /
    - conditions:
        - prefix: /onboard
      timeoutPolicy:
        response: 60s
      services:
        - name: onboard-service
          port: 6251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/onboard
            replacement: /
    - conditions:
        - prefix: /inventory
      timeoutPolicy:
        response: 60s
      services:
        - name: inventory-service
          port: 7251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/inventory
            replacement: /
    - conditions:
        - prefix: /metadata
      timeoutPolicy:
        response: 60s
      services:
        - name: metadata-service
          port: 6251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/metadata
            replacement: /
    - conditions:
        - prefix: /compliance
      timeoutPolicy:
        response: 60s
      services:
        - name: compliance-service
          port: 7251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/compliance
            replacement: /
    - conditions:
        - prefix: /schedule
      timeoutPolicy:
        response: 60s
      services:
        - name: describe-scheduler
          port: 5251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/schedule
            replacement: /
    - conditions:
        - prefix: /auth
      timeoutPolicy:
        response: 60s
      services:
        - name: auth-service
          port: 8251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/auth
            replacement: /
    - conditions:
        - prefix: /workspace
      timeoutPolicy:
        response: 60s
      services:
        - name: workspace-service
          port: 8351
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/workspace
            replacement: /
    - conditions:
        - prefix: /alerting
      timeoutPolicy:
        response: 60s
      services:
        - name: alerting-service
          port: 8000
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/alerting
            replacement: /
    - conditions:
        - prefix: /cost-estimator
      timeoutPolicy:
        response: 60s
      services:
        - name: cost-estimator-service
          port: 3351
      pathRewritePolicy:
        replacePrefix:
          - prefix: /{{ .Values.kaytu.workspace.name }}/cost-estimator
            replacement: /
