{{- if eq (.Values.kaytu.replicaCount | toString) "0" }}
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: kaytu
  name: "kaytu-core-{{ .Release.Namespace }}-alert-rules"
  namespace: prom-system
spec:
  groups:
    - name: scheduler
      rules:
#        - alert: KaytuComplianceSchedulerRunning
#          expr: count(kaytu_scheduler_schedule_compliance_job_total{status="successful"}) by (namespace) != count(kube_pod_info{pod=~"describe-scheduler.*"}) by (namespace)
#          for: 5m
#          labels:
#            severity: warning
#          annotations:
#            summary: 'All of Kaytu schedulers should run compliance job scheduling'
#            description: 'All of Kaytu schedulers should run compliance job scheduling'
#        - alert: NoKaytuComplianceSourceJob
#          expr: absent(kaytu_scheduler_schedule_compliance_source_job_total{status="successful"} > 0)
#          for: 4h
#          labels:
#            severity: warning
#          annotations:
#            summary: 'No schedule compliance source job happened in last 4 hours'
#            description: 'No schedule compliance source job happened in last 4 hours'
#        - alert: NoKaytuComplianceSourceJobDone
#          expr: absent(kaytu_compliance_worker_do_compliance_report_jobs_total{status="successful"} > 0)
#          for: 4h
#          labels:
#            severity: warning
#          annotations:
#            summary: 'No compliance source job has been done in last 4 hours'
#            description: 'No compliance source job has been done in last 4 hours'
        - alert: KaytuDescribeSchedulerRunning
          expr: absent(kaytu_scheduler_describe_jobs_total{status="successful"})
          for: 30m
          labels:
            severity: critical
          annotations:
            summary: 'All of Kaytu schedulers should run describe job scheduling'
            description: 'All of Kaytu schedulers should run describe job scheduling on namespace {{`{{ $labels.namespace }}`}}'
#        - alert: KaytuDescribeSchedulerFailed
#          expr: count(kaytu_scheduler_describe_jobs_total{status="failure"}) by (namespace) > 0
#          for: 10s
#          labels:
#            severity: critical
#          annotations:
#            summary: 'Kaytu schedulers failed'
#            description: 'Kaytu schedulers on namespace {{ `{{$labels.namespace}}` }}'
        - alert: KaytuDescribeSchedulerFailing
          expr: changes(kaytu_scheduler_describe_jobs_total{status="successful"}[20m]) == 0 and changes(kaytu_scheduler_describe_jobs_total{status="failure"}[20m]) > 10
          for: 20m
          labels:
            severity: critical
          annotations:
            summary: 'Kaytu schedulers failing'
            description: 'Kaytu schedulers failing on namespace {{ `{{$labels.namespace}}` }}'
        - alert: NoKaytuDescribeSourceJob
          expr: absent(kaytu_scheduler_describe_source_jobs_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule describe source job happened in last 12 hours'
            description: 'No schedule describe source job happened in last 12 hours'
#        - alert: KaytuDescribeSourceJobFailed
#          expr: count(kaytu_scheduler_describe_source_jobs_total{status="failure"}) by (namespace) > 0
#          for: 10s
#          labels:
#            severity: critical
#          annotations:
#            summary: 'Schedule describe source job failed'
#            description: 'Schedule describe source job failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuDescribeSourceJobsFailing
          expr: changes(kaytu_scheduler_describe_source_jobs_total{status="successful"}[20m]) == 0 and changes(kaytu_scheduler_describe_source_jobs_total{status="failure"}[20m]) > 10
          for: 20m
          labels:
            severity: critical
          annotations:
            summary: 'Schedule describe source jobs are failing'
            description: 'Schedule describe source jobs are failing'
        - alert: NoKaytuDescribeResourceJob
          expr: absent(kaytu_scheduler_describe_resource_jobs_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule describe resource job happened in last 12 hours'
            description: 'No schedule describe resource job happened in last 12 hours on namespace {{`{{ $labels.namespace }}`}}'
#        - alert: KaytuDescribeResourceJobFailed
#          expr: count(kaytu_scheduler_describe_resource_jobs_total{status="failure"}) by (namespace) > 0
#          for: 10s
#          labels:
#            severity: critical
#          annotations:
#            summary: 'Schedule describe resource job failed'
#            description: 'Schedule describe resource job failed'
        - alert: KaytuDescribeResourceJobsFailing
          expr: changes(kaytu_scheduler_describe_resource_jobs_total{status="successful"}[20m]) == 0 and changes(kaytu_scheduler_describe_resource_jobs_total{status="failure"}[20m]) > 10
          for: 20m
          labels:
            severity: critical
          annotations:
            summary: 'Schedule describe resource jobs are failing'
            description: 'Schedule describe resource jobs are failing namespace {{ `{{$labels.namespace}}` }}'
        - alert: NoKaytuSchedulerResultsProcessedTotal
          expr: absent(kaytu_scheduler_results_processed_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule results processed in last 12 hours'
            description: 'No schedule results processed in last 12 hours on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuSchedulerResultsProcessedTotalFailed
          expr: sum by (namespace) (rate(kaytu_scheduler_results_processed_total{status="failure"}[1m])) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Schedule results processed failed'
            description: 'Schedule results processed failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: NoKaytuSchedulerResourcesDescribed
          expr: absent(kaytu_scheduler_resources_described_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule resources described in last 12 hours'
            description: 'No schedule resources described in last 12 hours on namespace {{`{{ $labels.namespace }}`}}'
        - alert: NoKaytuSchedulerCleanupJobs
          expr: absent(kaytu_scheduler_cleanup_jobs_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule cleanup job last 12 hours'
            description: 'No schedule cleanup job in last 12 hours on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuSchedulerCleanupJobsFailed
          expr: sum by (namespace) (rate(kaytu_scheduler_cleanup_jobs_total{status="failure"}[1m])) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Schedule cleanup job failed'
            description: 'Schedule cleanup job failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: NoKaytuSchedulerResultsDelivered
          expr: absent(kaytu_scheduler_results_delivered_total > 0)
          for: 12h
          labels:
            severity: critical
          annotations:
            summary: 'No schedule results delivered in last 12 hours'
            description: 'No schedule results delivered in last 12 hours on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuSchedulerStreamFailed
          expr: sum by (namespace) (rate(kaytu_scheduler_stream_failure_total[1m])) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Schedule stream failed'
            description: 'Schedule stream failed on namespace {{`{{ $labels.namespace }}`}}'
#        - alert: NoKaytuDescribeSourceJobDone
#          expr: absent(kaytu_describe_worker_do_describe_jobs_total{status="successful"} > 0)
#          for: 4h
#          labels:
#            severity: warning
#          annotations:
#            summary: 'No describe source job has been done in last 4 hours'
#            description: 'No describe source job has been done in last 4 hours'
#        - alert: KaytuDescribeCleanupSchedulerRunning
#          expr: count(kaytu_scheduler_schedule_describe_cleanup_jobs_total{status="successful"}) by (namespace) != count(kube_pod_info{pod=~"describe-scheduler.*"}) by (namespace)
#          for: 5m
#          labels:
#            severity: warning
#          annotations:
#            summary: 'All of Kaytu schedulers should run describe cleanup job scheduling'
#            description: 'All of Kaytu schedulers should run describe cleanup job scheduling'
#        - alert: NoKaytuDescribeSourceCleanupJob
#          expr: absent(kaytu_scheduler_schedule_describe_cleanup_source_jobs_total > 0)
#          for: 4h
#          labels:
#            severity: warning
#          annotations:
#            summary: 'No schedule describe clean-up source job happened in last 4 hours'
#            description: 'No schedule describe clean-up source job happened in last 4 hours'
        - alert: KaytuQueueJobPublishingBlocked
          expr: kaytu_scheduler_queue_job_publishing_blocked > 0
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: 'Kaytu queue job publishing blocked'
            description: 'Kaytu queue job publishing blocked on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuHttp500Errors
          expr: sum by (namespace) (rate(kaytu_http_requests_total{status="5xx"}[1m])) > 0
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: 'Some 500 errors are happening in Kaytu HTTP endpoints'
            description: 'Some 500 errors are happening in Kaytu HTTP endpoints on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuComplianceJobFailed
          expr: increase(kaytu_scheduler_schedule_compliance_job_total{status="failure"}[10s]) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Some compliance jobs failed'
            description: '{{`{{ $value }}`}} compliance job(s) failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuAnalyticsJobFailed
          expr: increase(kaytu_scheduler_schedule_analytics_jobs_total{status="failure"}[10s]) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Some analytics jobs failed'
            description: '{{`{{ $value }}`}} analytics job(s) failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuSummarizerJobFailed
          expr: increase(kaytu_scheduler_schedule_summarizer_jobs_total{status="failure"}[10s]) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Some summarizer jobs failed'
            description: '{{`{{ $value }}`}} summarizer job(s) failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuInsightJobFailed
          expr: increase(kaytu_scheduler_schedule_insight_jobs_total{status="failure"}[10s]) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Some insight jobs failed'
            description: '{{`{{ $value }}`}} insight job(s) failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuCheckupJobFailed
          expr: increase(kaytu_scheduler_schedule_checkup_jobs_total{status="failure"}[10s]) > 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: 'Some checkup jobs failed'
            description: '{{`{{ $value }}`}} checkup job(s) failed on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuDescribePublishingBlocked
          expr: kaytu_scheduler_queue_job_publishing_blocked{queue_name="cloud queued"} == 1
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: 'Kaytu describe publishing queue is full'
            description: 'Kaytu describe publishing queue is full on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuLargeDescriberMessage
          expr: kaytu_scheduler_large_describe_resource_message == 1
          for: 10s
          labels:
            severity: test
          annotations:
            summary: 'Kaytu describe resource message is too large'
            description: 'Kaytu describe resource message is too large on resource type {{`{{ $labels.resource_type }}`}} on namespace {{`{{ $labels.namespace }}`}}'
        - alert: KaytuDescriberJobsFailing
          expr: (sum by (provider, namespace) (kaytu_scheduler_resources_described_total{status="failure"} / on(provider, namespace) group_left() sum by (provider, namespace) (kaytu_scheduler_resources_described_total))) > 0.06
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: 'Too many describer jobs failing'
            description: '{{ `{{ $value | printf "%.3f" }}` }} of the describer jobs failed for provider {{ `{{ $labels.provider }}` }} on namespace {{`{{ $labels.namespace }}`}}'
{{- end }}
