apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-pass-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {}
    error_log  /var/log/nginx/error.log  error;
    error_log  /dev/stderr  error;
    http {
      access_log  /var/log/nginx/access.log  main;
      access_log  /dev/stdout  main;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
      server {
        listen 80;

        location / {
          proxy_pass https://contour-envoy.contour-system.svc.cluster.local:443;
          proxy_ssl_verify off;
          proxy_ssl_server_name on;
          proxy_ssl_name {{ .Values.kaytu.domain.main }};
          proxy_set_header Host {{ .Values.kaytu.domain.main }};
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
        }
      }
    }
