---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-reporter
---
apiVersion: v1
kind: Secret
metadata:
  name: reporter-secret
  annotations:
    kubernetes.io/service-account.name: reporter
type: kubernetes.io/service-account-token
