apiVersion: v1
kind: Service
metadata:
  name: reporter-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: reporter-service
    monitoring: kaytu
spec:
  selector:
    app: reporter-service
  ports:
    - name: http
      port: 9251
      targetPort: 9251
  clusterIP: "None"
