---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: ca
  secretName: root-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: namespace-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: root-ca-tls
