apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy-grpc-external
  namespace: {{ .Release.Namespace }}
spec:
  virtualhost:
    fqdn: {{ .Values.kaytu.domain.grpc_external }}
    tls:
      secretName: {{ .Values.kaytu.domain.grpc_external }}
    authorization:
      extensionRef:
        apiVersion: projectcontour.io/v1alpha1
        name: auth
        namespace: {{ .Release.Namespace }}
      responseTimeout: 60s
  includes:
    - name: grpc-proxy-route
      namespace: {{ .Release.Namespace }}
