apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy
  namespace: {{ .Release.Namespace }}
spec:
  virtualhost:
    fqdn: ""
{{- if eq .Values.kaytu.ssl.enabled true }}
    tls:
      secretName: web-tls
{{- end }}
    authorization:
      extensionRef:
        apiVersion: projectcontour.io/v1alpha1
        name: auth
        namespace: {{ .Release.Namespace }}
      responseTimeout: 60s
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
        - content-type
        - data
        - sentry-trace
        - baggage
        - x-kaytu-demo
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
  includes:
    - name: http-proxy-route
      namespace: {{ .Release.Namespace }}
  routes:
    - conditions:
        - prefix: /api/kaytu/auth
      timeoutPolicy:
        response: 60s
      services:
        - name: auth-service
          port: 8251
      pathRewritePolicy:
        replacePrefix:
          - prefix: /api/kaytu/auth
            replacement: /
    - conditions:
        - prefix: /api/kaytu/workspace
      timeoutPolicy:
        response: 60s
      services:
        - name: workspace-service
          port: 8351
      pathRewritePolicy:
        replacePrefix:
          - prefix: /api/kaytu/workspace
            replacement: /
    - conditions:
        - prefix: /api/kaytu/subscription
      timeoutPolicy:
        response: 60s
      services:
        - name: subscription-service
          port: 8000
      pathRewritePolicy:
        replacePrefix:
          - prefix: /api/kaytu/subscription
            replacement: /
      authPolicy:
        disabled: true
    - conditions:
        - prefix: /dex
      timeoutPolicy:
        response: 60s
      services:
        - name: {{ .Release.Namespace }}-dex
          port: 5556
      authPolicy:
        disabled: true
    - conditions:
        - prefix: /docs/api/1.0
      services:
        - name: redoc
          port: 8080
      authPolicy:
        disabled: true
      pathRewritePolicy:
        replacePrefix:
          - prefix: /docs/api/1.0
            replacement: /
    - conditions:
        - prefix: /
      timeoutPolicy:
        response: 60s
      services:
        - name: frontend-v2-svc
          port: 7298
      authPolicy:
        disabled: true
