apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: workspaces-wildcard
  namespace: {{ .Release.Namespace }}
spec:
  delegations:
    - secretName: web-tls
      targetNamespaces:
        - "*"
