---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.kaytu.domain.grpc }}
  dnsNames:
    - {{ .Values.kaytu.domain.grpc }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: {{ .Values.kaytu.domain.grpc }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpc-external-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.kaytu.domain.grpc_external }}
  dnsNames:
    - {{ .Values.kaytu.domain.grpc_external }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: {{ .Values.kaytu.domain.grpc_external }}
