apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Namespace }}-pod-monitor
  namespace: prom-system
spec:
  podMetricsEndpoints:
    - port: http
  selector:
    matchLabels:
      monitoring: kaytu
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Namespace }}-service-monitor
  namespace: prom-system
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      monitoring: kaytu
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
