kaytu:
  agent:
    grpc_port: 8001
    image:
      name: "ghcr.io/kaytu-io/kaytu-agent"
      tag: ""
      pullSecret: ""
    storage:
      class: ""
      size: 1Gi
    tolerations: {}
    nodeSelector: {}
    affinity: {}
  kaytu:
    observabilityDays: 14
    apiKey: "XXX"
    prometheus:
      address: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
      auth:
        # for basic auth
        username: ""
        password: ""
        # for oauth2
        clientId: ""
        clientSecret: ""
        tokenUrl: ""
        scopesStr: ""
    # preferences for the optimize command e.g:
    # preferences:
    #   - service: "Kubernetes"
    #     key: "CPURequestBreathingRoom"
    #     value: "10"
    #   - service: "Kubernetes"
    #     key: "MinCpuRequest"
    #     value: "0.1"
    preferences: []