apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaytu-agent
  namespace: {{ .Release.Namespace }}
---
{{/* read access to nodes, namespaces, pods, deployments, stateful sets, daemons sets, jobs, cronjobs and services*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaytu-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaytu-agent
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kaytu-agent
subjects:
  - kind: ServiceAccount
    name: kaytu-agent
    namespace: {{ .Release.Namespace }}