apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaytu-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: kaytu-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaytu-agent
  template:
    metadata:
      labels:
        app: kaytu-agent
    spec:
      containers:
      - name: agent
        image: "kaytu.gh.io/kaytu-agent:{{ .Values.agent.version }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 8001
