---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insight-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-insight-worker
---
apiVersion: v1
kind: Secret
metadata:
  name: insight-worker-secret
  annotations:
    kubernetes.io/service-account.name: insight-worker
type: kubernetes.io/service-account-token
