apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-tls
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    tls.crt: {{ .Values.cloudflare.sealedTlsCrt }}
    tls.key: {{ .Values.cloudflare.sealedTlsKey }}

