{{- if eq .Values.kaytu.ssl.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-tls
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    tls.crt: {{ .Values.tls.sealedTlsCrt }}
    tls.key: {{ .Values.tls.sealedTlsKey }}
{{- end }}
