apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaytu-private
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    public: {{ .Values.kaytu.apikey.public }}
    private: {{ .Values.kaytu.apikey.private }}