apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: ghcr.io/fluent/fluent-operator/fluent-bit:3.1.5
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    requests:
      cpu: 10m
      memory: 25Mi
    limits:
      cpu: 500m
      memory: 200Mi
  fluentBitConfigName: fluent-bit-config
  tolerations:
    - operator: Exists
  envVars:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: cloudwatch-user
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: cloudwatch-user
          key: AWS_SECRET_ACCESS_KEY
  # hostNetwork: true
  # dnsPolicy: ClusterFirstWithHostNet

# ---
# apiVersion: fluentbit.fluent.io/v1alpha2
# kind: ClusterFilter
# metadata:
#   name: kubernetes
#   labels:
#     fluentbit.fluent.io/enabled: "true"
#     fluentbit.fluent.io/mode: "fluentbit-only"
# spec:
#   match: application.*
#   filters:
#   - kubernetes:
#       kubeURL: https://kuberntes.default.svc:443
#       kubeTagPrefix: application.var.log.containers.
#       mergeLog: true
#       mergeLogKey: log_processed
#       k8sLoggingParser: true
#       k8sLoggingExclude: false
#       labels: false
#       annotations: false
#       useKubelet: false
#       # kubeletPort: 10250
#       bufferSize: "0"


