apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "nack-{{ .Release.Namespace }}"
  namespace: "flux-system"
spec:
  chart:
    spec:
      chart: nack
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: 0.25.1
  values:
    jetstream:
      enabled: true

      nats:
        url: "nats://{{ .Release.Namespace }}-nats-{{ .Release.Namespace }}:4222"

    namespaced: true
  targetNamespace: "{{ .Release.Namespace }}"
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1m0s
