name: Digital Ocean Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release Charts","pages-build-deployment"]
    types:
      - completed

#   push:
#     branches:
#       - main

env:
  do_cluster_name: ${{ vars.DO_CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 ${{ env.do_cluster_name }}
      - uses: azure/setup-helm@v4.2.0
        name: Install Helm
      - name: Add Kaytu-charts helm repository
        run: helm repo add opengovernance https://${{ github.repository_owner }}.github.io/kaytu-charts && helm repo update
      - name: Install opengovernance
        run: helm install -n opengovernance opengovernance opengovernance/open-governance --create-namespace --timeout=10m